### ISSUE TITLE
Everything works, except audio.

### ISSUE THREAD

**Issue by Acetyld** [net32/VX5-591G#1]
Hello!
I tried all the id's for the audio. And a lot more, i tried VoodooHDA but i cant seem to get it working.

(and when it has more load the screen has short freezes/lags and gets worse with more load)

**Comment by net32** [comment]
Check if your config.plist have:

```
		<key>Audio</key>
		<dict>
			<key>#Inject</key>
			<string>0x0887</string>
			<key>AFGLowPowerState</key>
			<false/>
			<key>Inject</key>
			<integer>3</integer>
			<key>ResetHDA</key>
			<false/>
		</dict>
```

VoodooHDA It's not necessary, use AppleALC.kext
