### ISSUE TITLE
HDMI audio not work

### ISSUE THREAD

**Issue by lehmartins17** [net32/VX5-591G#2]
HDMI audio not work. I'm using Catalina 10.15.4, but it doesn't work on any version.

**Comment by net32** [comment]
I haven't tested it yet, I always use a USB Headset dongle.
I will try to find a solution!

**Comment by lehmartins17** [comment]
> I haven't tested it yet, I always use a USB Headset dongle.
> I will try to find a solution!

Please, please! Thanks, Thanks!

**Comment by sanderdsz** [comment]
Does your notebook native audio works? Just HDMI isn't?

**Comment by lehmartins17** [comment]
> Does your notebook native audio works? Just HDMI isn't?

Exact. The normal functional internal audio. The problem is hdmi audio. In the boot.log it shows that it has been recognized. But it doesn't work at all.

**...
5:467  0:000  found 2 handles with audio
5:467  0:000  No AudioIoDevice stored
5:467  0:000  no stored audio parameters
5:467  0:000  Found Audio Device Realtek ALC255 (Speaker) at index 0
5:467  0:000  Found Audio Device Realtek ALC255 (Headphones) at index 1
5:467  0:000  Found Audio Device Intel Kaby Lake HDMI (HDMI) at index 2
5:467  0:000  === [ InitXTheme ] ==============================
5:467  0:000  use night theme
5:476  0:009  Using theme 'Catalina' (EFI\CLOVER\themes\Catalina)
5:476  0:000  chosen theme Catalina
5:476  0:000  OS main and drive as badge
5:613  0:136  file sound read: sound_night.wav Not Found
5:614  0:000    Channels: 1  Sample rate: 44100 Hz  Bits: 16
5:614  0:000  output to channel 0 with volume 0, len=228736
5:614  0:000   sound channels=1 bits=16 freq=44100
5:614  0:000  sound play end with status=Not Found
5:746  0:132  theme inited
5:746  0:000  Chosen theme Catalina
5:746  0:000  after NVRAM boot-args=dart=0 -wegnoegpu -cdfon
5:746  0:000  === [ Dump SMC keys from NVRAM ] ================
5:746  0:000  found AppleSMC protocol
5:762  0:015  Registered 17 SMC keys
...**

**Comment by sanderdsz** [comment]
Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
Well any advices for me trying this for the first time?

**Comment by lehmartins17** [comment]
> Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
> Well any advices for me trying this for the first time?

use the net32 EFI which was the one that worked best for me. Apart from HDMI audio the rest worked.

**Comment by sanderdsz** [comment]
> > Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
> > Well any advices for me trying this for the first time?
> 
> use the net32 EFI which was the one that worked best for me. Apart from HDMI audio the rest worked.

Did you tried Mojave first to see if persist the audio problem? Or Catalina was your first try?

**Comment by lehmartins17** [comment]
> > > Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
> > > Well any advices for me trying this for the first time?
> > 
> > 
> > use the net32 EFI which was the one that worked best for me. Apart from HDMI audio the rest worked.
> 
> Did you tried Mojave first to see if persist the audio problem? Or Catalina was your first try?

first and only catalina

**Comment by sanderdsz** [comment]
> > > > Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
> > > > Well any advices for me trying this for the first time?
> > > 
> > > 
> > > use the net32 EFI which was the one that worked best for me. Apart from HDMI audio the rest worked.
> > 
> > 
> > Did you tried Mojave first to see if persist the audio problem? Or Catalina was your first try?
> 
> first and only catalina

May a ask you what did you used to mount the mac os installer? Olarila? OpenCore? Clover?

**Comment by lehmartins17** [comment]
> > > > > Im going to start this hackintosh tomorrow, well, if everything goes right I'll check the HDMI audio output.
> > > > > Well any advices for me trying this for the first time?
> > > > 
> > > > 
> > > > use the net32 EFI which was the one that worked best for me. Apart from HDMI audio the rest worked.
> > > 
> > > 
> > > Did you tried Mojave first to see if persist the audio problem? Or Catalina was your first try?
> > 
> > 
> > first and only catalina
> 
> May a ask you what did you used to mount the mac os installer? Olarila? OpenCore? Clover?

Olarila - Clover

**Comment by sanderdsz** [comment]
> Olarila - Clover

Strange, I can't even boot using Olarila - Clover, may I ask what steps you perform to create de USB installer? Just their tutorial?
I used Balena to flash de USB with their .raw file but no clue.

**Comment by lehmartins17** [comment]
> > Olarila - Clover
> 
> Strange, I can't even boot using Olarila - Clover, may I ask what steps you perform to create de USB installer? Just their tutorial?
> I used Balena to flash de USB with their .raw file but no clue.

use olarila EFI folder for chipset skylake+. Set trackpad to "Basic". Use Balena Etcher for making install USB

**Comment by sanderdsz** [comment]
Well I managed to reach everything.
The thing is that I'm worse than you, I'm without native audio and HDMI.

Do you have any clues about the internal audio from the system?

**Comment by sanderdsz** [comment]
Tried to apply AppleHDA patcher with Realtek ALC 255 but without luck.
Did you manage to do something besides put this EFI folder from net32 to get audio working?
This is so strange.

**Comment by net32** [comment]
@sanderdsz go to issue #1

**Comment by sanderdsz** [comment]
> @sanderdsz go to issue #1

Hi @net32 I'm sorry but can you be more specific on that problem? I'm using your exact config.plist from this repo, and that indicates exact the same code that you put over there.
Do I need to reinstall AppleALC.kext?

**Comment by lehmartins17** [comment]
> > @sanderdsz go to issue #1
> 
> Hi @net32 I'm sorry but can you be more specific on that problem? I'm using your exact config.plist from this repo, and that indicates exact the same code that you put over there.
> Do I need to reinstall AppleALC.kext?

First step is to update all kexts and the clover. Then test the layout-id in the audio. I use 3, but I patched DSDT.aml, but I knew that 30 or 28 work perfectly.

**Comment by lehmartins17** [comment]
> > > @sanderdsz go to issue #1
> > 
> > 
> > Hi @net32 I'm sorry but can you be more specific on that problem? I'm using your exact config.plist from this repo, and that indicates exact the same code that you put over there.
> > Do I need to reinstall AppleALC.kext?
> 
> First step is to update all kexts and the clover. Then test the layout-id in the audio. I use 3, but I patched DSDT.aml, but I knew that 30 or 28 work perfectly.

Also remember to include the CodecCommander if it is not on others. And if you experience wheezing or noise in the headset. Look for ALC255 jack fix. Quick and easy to do.

**Comment by lehmartins17** [comment]
> @sanderdsz go to issue #1

No HDMI audio? I'm running out of hope: '(

**Comment by lehmartins17** [comment]
@net32 
Were you able to find a solution for HDMI audio? It is still not working, it is the only thing left to be 100%. Give me that help please?

**Comment by net32** [comment]
Move to OpenCore -> https://github.com/net32/VX5-591G-OpenCore
